pipeline_config_id: runner_config

data:
  bistpp_nonseparable_mid_2:
    data_format: pkl
    train_dir: ./data/bistpp_nonseparable_mid_2/train.pkl
    valid_dir: ./data/bistpp_nonseparable_mid_2/dev.pkl
    test_dir: ./data/bistpp_nonseparable_mid_2/test.pkl
    data_specs:
      num_event_types: 2
      pad_token_id: 2
      padding_side: right

STNHP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: bistpp_nonseparable_mid_2
    runner_id: std_stpp
    model_id: STNHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 16
    max_epoch: 200
    shuffle: False
    optimizer: adam
    learning_rate: 5.e-4
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2
    gpu: 0
  model_config:
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    spatial_npoints: 10
    n_comps: 3
#    pretrained_model_dir: ./checkpoints/75518_4377527680_230530-132355/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


