pipeline_config_id: runner_config

data:
  stpp_exp_4:
    data_format: pkl
    train_dir: ./data/stpp_exp_4/train.pkl
    valid_dir: ./data/stpp_exp_4/dev.pkl
    test_dir: ./data/stpp_exp_4/test.pkl
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: right



RMTPP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: RMTPP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2019
    gpu: 0
  model_config:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5


RMTPP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    base_dir: './checkpoints/'
    model_id: RMTPP
  model_config:
    hidden_size: 32
    time_emb_size: 16
    mc_num_sample_per_step: 20
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    seed: 2019
    gpu: 0
    pretrained_model_dir: ./checkpoints/2555_4348724608_230603-155841/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 10

NHP_eval:
  base_config:
    stage: eval
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    base_dir: './checkpoints/'
    model_id: NHP
  trainer_config:
    batch_size: 256
    max_epoch: 1
  model_config:
    hidden_size: 64
    use_ln: False
    seed: 2019
    gpu: 0
    pretrained_model_dir: ./checkpoints/26507_4380788096_231111-101848/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5

NHP_gen:
  base_config:
    stage: eval
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: NHP # model name
    base_dir: './checkpoints/'
    trainer_config:
      batch_size: 256
      max_epoch: 20
      shuffle: False
      optimizer: adam
      learning_rate: 1.e-3
      valid_freq: 1
      use_tfb: False
      metrics: [ 'acc', 'rmse' ]
      seed: 2019
      gpu: 0
    model_config:
      hidden_size: 64
      loss_integral_num_sample_per_step: 20
      pretrained_model_dir: ./checkpoints/75518_4377527680_230530-132355/models/saved_model
      thinning:
        num_seq: 10
        num_sample: 1
        num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
        look_ahead_time: 10
        patience_counter: 5 # the maximum iteration used in adaptive thinning
        over_sample_rate: 5
        num_samples_boundary: 5
        dtime_max: 5
        num_step_gen: 1

FullyNN_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: FullyNN # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2019
    gpu: 0
  model_config:
    rnn_type: LSTM
    hidden_size: 32
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    model_specs:
      num_mlp_layers: 3
#    thinning:
#      num_seq: 10
#      num_sample: 1
#      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
#      look_ahead_time: 10
#      patience_counter: 5 # the maximum iteration used in adaptive thinning
#      over_sample_rate: 5
#      num_samples_boundary: 5
#      dtime_max: 5
#      num_step_gen: 1



IntensityFree_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: IntensityFree # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2019
    gpu: 0
  model_config:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    model_specs:
      num_mix_components: 3



ODETPP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: ODETPP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 200
    shuffle: False
    optimizer: adam
    learning_rate: 3.e-2 # 1.e-1
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2021
    gpu: 0
  model_config:
    hidden_size: 4
    time_emb_size: 4
    num_layers: 1
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    model_specs:
      ode_num_sample_per_step: 101 # 2
      time_factor: 1 # 100
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 50 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1

ODETPP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    base_dir: './checkpoints/'
    model_id: ODETPP
  trainer_config:
    batch_size: 256
    max_epoch: 1
  model_config:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 1
    sharing_param_layer: False
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: False
    seed: 2019
    gpu: 0
    pretrained_model_dir: ./checkpoints/3538_4310828416_230603-165911/models/saved_model
    model_specs:
      ode_num_sample_per_step: 2
      time_factor: 100
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 10

STNHP_3_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: STNHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 16
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2020
    gpu: 0
  model_config:
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    n_comps: 3
    spatial_npoints: 10
#    pretrained_model_dir: ./checkpoints/75518_4377527680_230530-132355/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


STNHP_4_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: STNHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 16
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2020
    gpu: 0
  model_config:
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    n_comps: 4
    spatial_npoints: 10
#    pretrained_model_dir: ./checkpoints/75518_4377527680_230530-132355/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


STNHP_5_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stpp_exp_4
    runner_id: std_stpp
    model_id: STNHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 16
    max_epoch: 100
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2020
    gpu: 0
  model_config:
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    n_comps: 5
    spatial_npoints: 10
#    pretrained_model_dir: ./checkpoints/75518_4377527680_230530-132355/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1



