data_config:
  train_dir: ./data/gtd_pakistan/train.pkl
  valid_dir: ./data/gtd_pakistan/dev.pkl
  test_dir: ./data/gtd_pakistan/test.pkl
  data_format: pkl
  data_specs:
    num_event_types: 2
    pad_token_id: 2
    padding_side: right
    truncation_side: null
    padding_strategy: null
    truncation_strategy: null
    max_len: null
base_config:
  stage: train
  backend: torch
  dataset_id: gtd_pakistan
  runner_id: std_stpp
  model_id: STNHP
  base_dir: ./checkpoints/
model_config:
  rnn_type: LSTM
  hidden_size: 64
  time_emb_size: 16
  num_layers: 2
  mc_num_sample_per_step: 20
  sharing_param_layer: false
  loss_integral_num_sample_per_step: 50
  dropout_rate: 0.0
  use_ln: false
  thinning:
    num_seq: 10
    num_sample: 1
    num_exp: 500
    look_ahead_time: 10
    patience_counter: 5
    over_sample_rate: 5
    num_samples_boundary: 5
    dtime_max: 5
    num_step_gen: 1
  num_event_types_pad: 3
  num_event_types: 2
  event_pad_index: 2
  model_id: STNHP
  pretrained_model_dir: null
  gpu: 0
  model_specs: {}
trainer_config:
  seed: 201
  gpu: 0
  batch_size: 13
  max_epoch: 200
  shuffle: false
  optimizer: adam
  learning_rate: 0.0007
  valid_freq: 1
  use_tfb: false
  metrics:
  - acc
  - rmse
